# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserCreate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, username: str=None, password: str=None, email: str=None):  # noqa: E501
        """UserCreate - a model defined in Swagger

        :param username: The username of this UserCreate.  # noqa: E501
        :type username: str
        :param password: The password of this UserCreate.  # noqa: E501
        :type password: str
        :param email: The email of this UserCreate.  # noqa: E501
        :type email: str
        """
        self.swagger_types = {
            'username': str,
            'password': str,
            'email': str
        }

        self.attribute_map = {
            'username': 'username',
            'password': 'password',
            'email': 'email'
        }
        self._username = username
        self._password = password
        self._email = email

    @classmethod
    def from_dict(cls, dikt) -> 'UserCreate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserCreate of this UserCreate.  # noqa: E501
        :rtype: UserCreate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this UserCreate.


        :return: The username of this UserCreate.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this UserCreate.


        :param username: The username of this UserCreate.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def password(self) -> str:
        """Gets the password of this UserCreate.


        :return: The password of this UserCreate.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this UserCreate.


        :param password: The password of this UserCreate.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def email(self) -> str:
        """Gets the email of this UserCreate.


        :return: The email of this UserCreate.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this UserCreate.


        :param email: The email of this UserCreate.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email
