# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, username: str=None, email: str=None, score: int=None):  # noqa: E501
        """UserResponse - a model defined in Swagger

        :param id: The id of this UserResponse.  # noqa: E501
        :type id: str
        :param username: The username of this UserResponse.  # noqa: E501
        :type username: str
        :param email: The email of this UserResponse.  # noqa: E501
        :type email: str
        :param score: The score of this UserResponse.  # noqa: E501
        :type score: int
        """
        self.swagger_types = {
            'id': str,
            'username': str,
            'email': str,
            'score': int
        }

        self.attribute_map = {
            'id': 'id',
            'username': 'username',
            'email': 'email',
            'score': 'score'
        }
        self._id = id
        self._username = username
        self._email = email
        self._score = score

    @classmethod
    def from_dict(cls, dikt) -> 'UserResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserResponse of this UserResponse.  # noqa: E501
        :rtype: UserResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this UserResponse.


        :return: The id of this UserResponse.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this UserResponse.


        :param id: The id of this UserResponse.
        :type id: str
        """

        self._id = id

    @property
    def username(self) -> str:
        """Gets the username of this UserResponse.


        :return: The username of this UserResponse.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this UserResponse.


        :param username: The username of this UserResponse.
        :type username: str
        """

        self._username = username

    @property
    def email(self) -> str:
        """Gets the email of this UserResponse.


        :return: The email of this UserResponse.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this UserResponse.


        :param email: The email of this UserResponse.
        :type email: str
        """

        self._email = email

    @property
    def score(self) -> int:
        """Gets the score of this UserResponse.


        :return: The score of this UserResponse.
        :rtype: int
        """
        return self._score

    @score.setter
    def score(self, score: int):
        """Sets the score of this UserResponse.


        :param score: The score of this UserResponse.
        :type score: int
        """

        self._score = score
